MuscleMagic/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;


namespace MuscleMagic.Controllers
{
    public class ExerciseController : Controller
    {
        
        public IActionResult Muscle_group_selection()
        {
            return View();
        }
    }
}

MuscleMagic/Controllers/ProgramController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MuscleMagic.Models;




namespace MuscleMagic.Controllers
{
    public class ProgramController : Controller
    {
       
        [Authorize]
        public IActionResult Programs()
        {
            using (MMcontext db = new MMcontext())
            {
                var vm = new ExerciseListViewModel();
                string getemail = HttpContext.Session.GetString("email");
                var userid = db.Users.Where(u => u.Email == getemail).FirstOrDefault();
                var programid = db.Programs.Where(u => u.ProgramName == "Upper/Lower").FirstOrDefault();
                vm.UserId = userid.Id;
                vm.ProgramId = programid.Id;

                
                var exerciselist1 = new List<Exercise>();
                var exerciselist2 = new List<Exercise>();
                var exerciselist3 = new List<Exercise>();
                var exerciselist4 = new List<Exercise>();
                var exercise1 = db.Exercises.Find(1);
                var exercise2 = db.Exercises.Find(2);
                var exercise3 = db.Exercises.Find(3);
                var exercise4 = db.Exercises.Find(4);
                var exercise5 = db.Exercises.Find(5);
                var exercise6 = db.Exercises.Find(6);
                var exercise7 = db.Exercises.Find(7);
                var exercise8 = db.Exercises.Find(8);
                var exercise9 = db.Exercises.Find(9);
                var exercise10 = db.Exercises.Find(10);
                var exercise11 = db.Exercises.Find(11);
                var exercise12 = db.Exercises.Find(12);
                var exercise13 = db.Exercises.Find(13);
                var exercise14 = db.Exercises.Find(14);
                var exercise15 = db.Exercises.Find(15);
                var exercise16 = db.Exercises.Find(16);
                var exercise17 = db.Exercises.Find(17);
                var exercise18 = db.Exercises.Find(18);
                var exercise19 = db.Exercises.Find(19);
                var exercise20 = db.Exercises.Find(20);
                var exercise21 = db.Exercises.Find(21);
                var exercise22 = db.Exercises.Find(22);
                var exercise23 = db.Exercises.Find(23);
                var exercise24 = db.Exercises.Find(24);
                var exercise25 = db.Exercises.Find(25);
                exerciselist1.Add(exercise1);
                exerciselist1.Add(exercise2);
                exerciselist1.Add(exercise3);
                exerciselist1.Add(exercise4);
                exerciselist1.Add(exercise5);
                exerciselist1.Add(exercise6);
                exerciselist1.Add(exercise7);
                exerciselist2.Add(exercise8);
                exerciselist2.Add(exercise9);
                exerciselist2.Add(exercise10);
                exerciselist2.Add(exercise11);
                exerciselist2.Add(exercise12);
                exerciselist2.Add(exercise13);
                exerciselist3.Add(exercise14);
                exerciselist3.Add(exercise15);
                exerciselist3.Add(exercise16);
                exerciselist3.Add(exercise17);
                exerciselist3.Add(exercise18);
                exerciselist3.Add(exercise19);
                exerciselist4.Add(exercise20);
                exerciselist4.Add(exercise21);
                exerciselist4.Add(exercise22);
                exerciselist4.Add(exercise23);
                exerciselist4.Add(exercise24);
                exerciselist4.Add(exercise25);

                vm.exerciselist1 = exerciselist1;
                vm.exerciselist2 = exerciselist2;
                vm.exerciselist3 = exerciselist3;
                vm.exerciselist4 = exerciselist4;
                return View(vm);
            }
          
        }
        public IActionResult AddProgramtoUser(int id, int id2)
        {
            using (MMcontext db = new MMcontext())
            {
                
                var ProgramUser = db.Programs.Find(id);
                var UserProgram  = db.Users.Find(id2);
                ProgramUser.Users = new List<User>();
                UserProgram.Programs = new List<Exerciseschedule>();
                ProgramUser.Users.Add(UserProgram);
                UserProgram.Programs.Add(ProgramUser);

                if (UserProgram.Programs.Where(o => o.Id == id).Count() == 1)
                {
                    db.Entry(ProgramUser).State = EntityState.Modified;
                    db.SaveChanges();
                    db.Entry(UserProgram).State = EntityState.Modified;
                    db.SaveChanges();
                }

                return RedirectToAction("Myaccount", "Home");
            }
            
        }
    }
}

MuscleMagic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/media.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap"
          rel="stylesheet" />
    <script src="https://kit.fontawesome.com/e58fdfd909.js" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav>
        <div class="logo">
            <a asp-action="Index" asp-controller="Home">
                <h2>MUSCLE MAGIC</h2>
            </a>
        </div>
        <ul class="nav-links">
            <li>
                <a asp-action="Myaccount" asp-controller="Home">My Account</a>
            </li>
            <li>
                <a asp-action="Muscle_group_selection" asp-controller="Exercise">Exercises</a>
            </li>
            <li>
                <a asp-action="Programs" asp-controller="Program">Programs</a>
            </li>
        </ul>
        <div class="login">
            @if (User.Identity.IsAuthenticated)
            {
                <input type="button" value="Log Out" onclick="location.href='@Url.Action("SignOutUser", "Home")'" />
            }
            else
            {
                <button class="loginbtn">Log in / Register</button>
            }
        </div>
        <div class="burger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>
            @if (!User.Identity.IsAuthenticated)
            {
                <div class="loginsignup-container">
                    <div class="loginsignup" id="loginsignup">
                        <div class="form-container sign-up-container">
                            <form onsubmit="return false;">
                                <h1>Create Account</h1>
                                <div class="social-container">
                                    <a href="#" class="fb"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#" class="social">
                                        <i class="fab fa-google-plus-g"></i>
                                    </a>
                                    <a href="#" class="social">
                                        <i class="fab fa-linkedin-in"></i>
                                    </a>
                                </div>
                                <span>or use your email for registration</span>
                                <input id="fname" type="text" placeholder="Firstname" />
                                <input id="lname" type="text" placeholder="Lastname" />
                                <input id="email" type="text" placeholder="Email" />
                                <input id="password" type="password" placeholder="Password" />
                                <div id="errormsg"></div>
                                <button class="signup-in" id="register">Sign Up</button>
                                <button id="cancel-modal1">Cancel</button>
                            </form>
                        </div>
                        <div class="form-container sign-in-container">
                           <form onsubmit="return false;">
                               <h1>Sign in</h1>
                               <div class="social-container">
                                   <a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
                                   <a href="#" class="social">
                                       <i class="fab fa-google-plus-g"></i>
                                   </a>
                                   <a href="#" class="social">
                                       <i class="fab fa-linkedin-in"></i>
                                   </a>
                               </div>
                               <span>or use your account</span>
                               <input id="email2" type="text" placeholder="Email" />
                               <input id="password2" type="password" placeholder="Password" />

                               <div id="incorrect-credentials"></div>
                               <button class="signup-in" id="login">Sign In</button>
                               <button id="cancel-modal2">Cancel</button>
                           </form>
                        </div>
                        <div class="overlay-container">
                            <div class="overlay">
                                <div class="overlay-panel overlay-left">
                                    <h1>Hey big guy</h1>
                                    <p>
                                        Log in here to continue your journey to becoming swole
                                    </p>
                                    <button class="ghost" id="signIn">Sign In</button>
                                </div>
                                <div class="overlay-panel overlay-right">
                                    <h1>Hello, Friend!</h1>
                                    <p>
                                        Register here and start your journey to becoming swole with us
                                    </p>
                                    <button class="ghost" id="signUp">Sign Up</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            }
       
    @RenderBody()
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="~/js/site.js"></script>
</body>
</html>